INSERT INTO `events` (`event_id`, `created_at`, `updated_at`)
VALUES (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), NOW(), NOW());
INSERT INTO `events` (`event_id`, `created_at`, `updated_at`)
VALUES (UUID_TO_BIN('45b2e9d2-5a21-4d1a-8c9e-5f8e5b4e3f17'), NOW(), NOW());
INSERT INTO `events` (`event_id`, `created_at`, `updated_at`)
VALUES (UUID_TO_BIN('d8f1e6c3-9a7b-4d4f-b6e1-5c8e3b7d2e0a'), NOW(), NOW());

INSERT INTO `accounts` (`kakao_oauth_id`, `name`, `email`, `initial_role_granted_flag`, `linkedin_url`, `github_url`,
                        `instagram_url`, `created_at`, `updated_at`)
VALUES (3874198647, '권나연', 'chichoc.dev@gmail.com', true, null, 'https://github.com/chichoc', null, NOW(), NOW()),
       (100000002, '이영희', 'lee.younghee@example.com', true, 'https://linkedin.com/in/leeyounghee',
        'https://github.com/leeyounghee', 'https://instagram.com/leeyounghee', NOW(), NOW()),
       (100000003, '박민수', 'park.minsu@example.com', true, 'https://linkedin.com/in/parkminsu',
        'https://github.com/parkminsu', 'https://instagram.com/parkminsu', NOW(), NOW()),
       (100000004, '정수진', 'jung.sujin@example.com', true, 'https://linkedin.com/in/jungsujin',
        'https://github.com/jungsujin', 'https://instagram.com/jungsujin', NOW(), NOW()),
       (100000005, '최동현', 'choi.donghyun@example.com', true, 'https://linkedin.com/in/choidonghyun',
        'https://github.com/choidonghyun', 'https://instagram.com/choidonghyun', NOW(), NOW()),
       (100000006, '강지은', 'kang.jieun@example.com', true, 'https://linkedin.com/in/kangjieun',
        'https://github.com/kangjieun', 'https://instagram.com/kangjieun', NOW(), NOW()),
       (100000007, '윤태호', 'yoon.taeho@example.com', true, 'https://linkedin.com/in/yoontaeho',
        'https://github.com/yoontaeho', 'https://instagram.com/yoontaeho', NOW(), NOW()),
       (100000008, '한소영', 'han.soyoung@example.com', true, 'https://linkedin.com/in/hansoyoung',
        'https://github.com/hansoyoung', 'https://instagram.com/hansoyoung', NOW(), NOW()),
       (100000009, '송재현', 'song.jaehyun@example.com', true, 'https://linkedin.com/in/songjaehyun',
        'https://github.com/songjaehyun', 'https://instagram.com/songjaehyun', NOW(), NOW()),
       (100000010, '임하나', 'lim.hana@example.com', true, 'https://linkedin.com/in/limhana', 'https://github.com/limhana',
        'https://instagram.com/limhana', NOW(), NOW()),
       (100000011, '오승우', 'oh.seungwoo@example.com', true, 'https://linkedin.com/in/ohseungwoo',
        'https://github.com/ohseungwoo', 'https://instagram.com/ohseungwoo', NOW(), NOW()),
       (100000012, '배미영', 'bae.miyeong@example.com', true, 'https://linkedin.com/in/baemiyeong',
        'https://github.com/baemiyeong', 'https://instagram.com/baemiyeong', NOW(), NOW()),
       (100000013, '조현우', 'jo.hyunwoo@example.com', true, 'https://linkedin.com/in/johyunwoo',
        'https://github.com/johyunwoo', 'https://instagram.com/johyunwoo', NOW(), NOW()),
       (100000014, '신지원', 'shin.jiwon@example.com', true, 'https://linkedin.com/in/shinjiwon',
        'https://github.com/shinjiwon', 'https://instagram.com/shinjiwon', NOW(), NOW()),
       (100000015, '류동훈', 'ryu.donghoon@example.com', true, 'https://linkedin.com/in/ryudonghoon',
        'https://github.com/ryudonghoon', 'https://instagram.com/ryudonghoon', NOW(), NOW()),
       (100000016, '남지현', 'nam.jihyun@example.com', true, 'https://linkedin.com/in/namjihyun',
        'https://github.com/namjihyun', 'https://instagram.com/namjihyun', NOW(), NOW()),
       (100000017, '백준호', 'baek.junho@example.com', true, 'https://linkedin.com/in/baekjunho',
        'https://github.com/baekjunho', 'https://instagram.com/baekjunho', NOW(), NOW()),
       (100000018, '곽서연', 'gwak.seoyeon@example.com', true, 'https://linkedin.com/in/gwakseoyeon',
        'https://github.com/gwakseoyeon', 'https://instagram.com/gwakseoyeon', NOW(), NOW()),
       (100000019, '문성민', 'moon.sungmin@example.com', true, 'https://linkedin.com/in/moonsungmin',
        'https://github.com/moonsungmin', 'https://instagram.com/moonsungmin', NOW(), NOW()),
       (100000020, '양은지', 'yang.eunji@example.com', true, 'https://linkedin.com/in/yangeunji',
        'https://github.com/yangeunji', 'https://instagram.com/yangeunji', NOW(), NOW());

INSERT INTO `profiles` (`event_id`, `account_id`, `pin_number`, `icon_number`, `introduce`, `proudest_experience`,
                        `tough_experience`, `created_at`, `updated_at`)
VALUES (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 1, 2841, 1,
        '안녕하세요! 프론트엔드 개발자 권나연입니다. React와 TypeScript를 주로 사용해요.', '대학생 때 만든 웹앱이 10만 다운로드를 달성했어요!',
        '처음 React를 배울 때 상태 관리가 너무 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 2, 1002, 2, '백엔드 개발자 이영희입니다. Spring Boot와 JPA를 전문으로 해요.',
        '대규모 트래픽을 처리하는 시스템을 구축했어요.', '데이터베이스 성능 최적화가 가장 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 3, 1003, 3, '풀스택 개발자 박민수입니다. MERN 스택을 주로 사용해요.',
        '스타트업에서 0부터 1까지 제품을 만들어봤어요.', '서버 배포와 인프라 관리가 처음엔 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 4, 1004, 4, 'UI/UX 디자이너 정수진입니다. 사용자 경험을 중요하게 생각해요.',
        '대기업 프로젝트에서 디자인 시스템을 구축했어요.', '개발자와의 소통이 가장 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 5, 1005, 5, '데이터 엔지니어 최동현입니다. 빅데이터 처리와 분석을 전문으로 해요.',
        '실시간 데이터 파이프라인을 구축했어요.', '대용량 데이터 처리 최적화가 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 6, 1006, 6, '모바일 앱 개발자 강지은입니다. iOS와 Android 모두 개발해요.',
        '앱스토어에서 5점 만점을 받은 앱을 만들었어요.', '크로스 플랫폼 개발의 호환성 문제가 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 7, 1007, 7, 'DevOps 엔지니어 윤태호입니다. 클라우드 인프라를 관리해요.',
        '마이크로서비스 아키텍처를 구축했어요.', '서비스 무중단 배포 구현이 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 8, 1008, 8, 'QA 엔지니어 한소영입니다. 품질 보증과 테스트 자동화를 담당해요.',
        '테스트 자동화로 버그 발견률을 80% 향상시켰어요.', '복잡한 비즈니스 로직 테스트 설계가 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 9, 1009, 9, '보안 엔지니어 송재현입니다. 애플리케이션 보안을 전문으로 해요.',
        '보안 취약점을 발견해 회사를 위기에서 구했어요.', '새로운 보안 위협에 대한 대응이 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 10, 1010, 10, 'AI/ML 엔지니어 임하나입니다. 머신러닝 모델을 개발해요.',
        '추천 시스템을 구현해 매출을 30% 증가시켰어요.', '데이터 전처리와 모델 튜닝이 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 11, 1011, 11, '블록체인 개발자 오승우입니다. 스마트 컨트랙트를 개발해요.',
        'DeFi 프로젝트를 성공적으로 런칭했어요.', '블록체인의 확장성 문제 해결이 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 12, 1012, 12, '게임 개발자 배미영입니다. Unity와 Unreal Engine을 사용해요.',
        '인디 게임을 만들어 수천 명의 플레이어를 확보했어요.', '게임 최적화와 성능 튜닝이 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 13, 1013, 13, '시스템 프로그래머 조현우입니다. 저수준 프로그래밍을 전문으로 해요.',
        '운영체제 커널 모듈을 개발했어요.', '메모리 관리와 동시성 제어가 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 14, 1014, 14, '프로덕트 매니저 신지원입니다. 제품 기획과 개발을 조율해요.',
        '사용자 만족도가 높은 제품을 성공적으로 출시했어요.', '개발팀과 디자인팀 간의 조율이 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 15, 1015, 15, '기술 리드 류동훈입니다. 개발팀을 이끌고 기술적 의사결정을 해요.',
        '팀 생산성을 50% 향상시키는 프로세스를 구축했어요.', '팀원들의 기술 수준 차이를 극복하는 것이 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 16, 1016, 16, '프론트엔드 아키텍트 남지현입니다. 프론트엔드 아키텍처를 설계해요.',
        '대규모 프론트엔드 프로젝트의 아키텍처를 설계했어요.', '레거시 코드 리팩토링이 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 17, 1017, 17, '백엔드 아키텍트 백준호입니다. 백엔드 시스템 아키텍처를 설계해요.',
        '마이크로서비스 아키텍처를 도입해 시스템 안정성을 높였어요.', '서비스 간 의존성 관리가 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 18, 1018, 18, '데이터 사이언티스트 곽서연입니다. 데이터 분석과 인사이트 도출을 해요.',
        '고객 행동 분석으로 매출 증대에 기여했어요.', '데이터 품질 문제 해결이 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 19, 1019, 19, '클라우드 아키텍트 문성민입니다. 클라우드 인프라 설계를 전문으로 해요.',
        '멀티 클라우드 환경을 구축해 비용을 40% 절약했어요.', '클라우드 서비스 간 마이그레이션이 어려웠어요.', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 20, 1020, 20, '사이버보안 전문가 양은지입니다. 보안 정책과 위험 관리를 담당해요.',
        '보안 사고 대응 체계를 구축해 위험을 최소화했어요.', '새로운 보안 위협에 대한 대응 체계 구축이 어려웠어요.', NOW(), NOW());

INSERT INTO `relations` (`first_profile_id`, `second_profile_id`, `created_at`, `updated_at`)
VALUES (1, 2, NOW(), NOW()),
       (1, 3, NOW(), NOW()),
       (1, 4, NOW(), NOW()),
       (1, 5, NOW(), NOW()),
       (1, 6, NOW(), NOW()),
       (1, 7, NOW(), NOW()),
       (1, 8, NOW(), NOW()),
       (1, 9, NOW(), NOW()),
       (1, 10, NOW(), NOW()),
       (1, 11, NOW(), NOW());
